### ISSUE TITLE
There appears a lot of zombie process after long term use

### ISSUE THREAD

**Issue by zerofancy** [thibaultmeyer/bingwallpaper#1]
![image](https://github.com/thibaultmeyer/bingwallpaper/assets/40628516/69017adc-060c-4492-b2c9-5e705fb2972b)

**Comment by thibaultmeyer** [comment]
Hello,

Thank you for your bug report. I will investigate the problem.  Do you have other informations about you system (Os version, Swift version, ...) ?

**Comment by zerofancy** [comment]
> Hello,
> 
> Thank you for your bug report. I will investigate the problem. Do you have other informations about you system (Os version, Swift version, ...) ?

OS: macOS 14.1 23B74 arm64
Host: Mac14,9
Kernel: 23.1.0
Resolution: 1512x982, 1920x1080

Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0

**Comment by thibaultmeyer** [comment]
I'm reproducing the problem too, I'm preparing a patch.

**Comment by thibaultmeyer** [comment]
Hi @zerofancy,

issue fixed, you can now download the version 1.0.1 : https://github.com/thibaultmeyer/bingwallpaper/releases/tag/release%2F1.0.1
