### ISSUE TITLE
Text overlay not showing 

### ISSUE THREAD

**Issue by mrlee14** [thibaultmeyer/bingwallpaper#15]
bingwallpaper version 1.5.0 (linux/x86_64)

CONFIG:
```
image_dimension_width = 2560
image_dimension_height = 1440
text_overlay_position = "TOP_RIGHT"
target_filename = "/home/user44/.wallpapers/bingwallpaper.png"
```

CMD:
`bingwallpaper -c /home/user44/.config/bingwallpaper/bingwallpaper.conf > /tmp/bingwallpaper.log`

RESULT:
```
thread 'main' panicked at src/bingwallpaper/textoverlay.rs:49:89:
called `Result::unwrap()` on an `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(Format(FormatError { inner: InvalidSignature })) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thibaultmeyer** [comment]
Hi @mrlee14 

I reproduce the error. It seems occur because the library detect file format (PNG, JPG, ...) from the filename (bad practice). As workaround, you can edit your configuration file to change file extension from `.png` to `.jpg` (file downloaded from Bing is really in JPG format).
