### ISSUE TITLE
Add Virtual Desktop Support?

### ISSUE THREAD

**Issue by theSoberSobber** [thibaultmeyer/bingwallpaper#3]
The original bing wallpaper app does not respect virtual desktops and sets the wall only on whatever Virtual Desktop is Active right now only. Then all virtual desktops start looking erratic, so I request you to add Virtual Desktop Support.
You may wanna look into ciantic's Virtual Desktop Accessor (which is also written in rust).

**Comment by theSoberSobber** [comment]
Hey @thibaultmeyer I have more information that hopefully makes it easier to implement, 
all VD Wallpapers are stored at `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\VirtualDesktops\Desktops\{VD-ID}`
You can use the `fn GetDesktopCount() -> i32` and `fn GetDesktopIdByNumber(number: i32) -> GUID` functions from [here](https://github.com/Ciantic/VirtualDesktopAccessor).

I don't know rust or I would've made a pr. I really don't wanna learn rust just for this :((

**Comment by thibaultmeyer** [comment]
hello,

I'll see what I can do to upgrade the software with this new feature.

Thank you for your suggestion.


**Crates** 

- https://crates.io/crates/winvd
- https://crates.io/crates/winver

**Comment by thibaultmeyer** [comment]
@theSoberSobber 

I've added virtual desktop support for Windows. You can download version 1.1.0 from the following page: https://github.com/thibaultmeyer/bingwallpaper/releases/tag/release%2F1.1.0

**Comment by theSoberSobber** [comment]
@thibaultmeyer Dude, thank you so much, omg!
I suggest you put this up as a highlight of your project too, since this really distinguishes yours from the other script/official clients!
Once again thanks for the awesome work!

**Comment by theSoberSobber** [comment]
Btw, just for the sake of efficiency, there is an inbuilt function in IVirtualDesktopManagerInternal called UpdateAllDesktopPaths, you can read more about it [here](https://github.com/MScholtes/VirtualDesktop/blob/master/VirtualDesktop11-23H2.cs#L183).
