### ISSUE TITLE
 which is default change/check interval for loop -l option

### ISSUE THREAD

**Issue by mrlee14** [thibaultmeyer/bingwallpaper#9]
It says on help print "every hours", is this typo meaning "every hour"? Also can i change it in the config?

**Comment by thibaultmeyer** [comment]
Hello,

if you run application at 3h12 PM, next check will be at 4h12 PM. Remember that the Bing wallpaper only changes once a day.

If you'd like, I can look into adding an option to change the default value (1 hour) to check more quickly or less quickly for the presence of a new wallpaper ?

**Comment by mrlee14** [comment]
> Hello,
> 
> if you run application at 3h12 PM, next check will be at 4h12 PM. Remember that the Bing wallpaper only changes once a day.
> 
> If you'd like, I can look into adding an option to change the default value (1 hour) to check more quickly or less quickly for the presence of a new wallpaper ?

Yes, in case I decide to not use cron then interval config option would be great perhaps every 4 or 8 hours eg. -loop 4  or -loop 8 I think this is useful option or even better maybe once a day not via cron but some internal stamping…

**Comment by mrlee14** [comment]
Also via cron is not working exactly as it should, I have fedora 38 system and I does partly job but not always, will describe in new ticket when I have time… good work, actually it’s pulling bing wallpapers to fit my resolution, before I had some python bw but only single resolution support.

**Comment by thibaultmeyer** [comment]
Finally, the documentation was wrong :( When using `--loop`, a new wallpaper is checked every 900 seconds (15 minutes).

I've added the `loop_interval_second` option to the configuration file so that I can customize the value. You can try it with the version `1.4.0`.
